const authentication = require("./authentication");
const changeHistory = require("./changeHistory");
const company = require("./company");
const department = require("./department");
const document = require("./document");
const employee = require("./employee");
const employeeAnnualTimeOff = require("./employeeAnnualTimeOff");
const permission = require("./permission");
const reportTo = require("./reportTo");
const role = require("./role");
const socialProfile = require("./socialProfile");
const team = require("./team");
const timeOff = require("./timeOff");
const timeOffHistory = require("./timeOffHistory");
const appUser = require("./appUser");
const offBoarding = require("./offBoarding");
const offBoardingQuestion = require("./offBoardingQuestion");
const offBoardingResponse = require("./offBoardingResponse");
const offBoardingDocument = require("./offBoardingDocument");
const notification = require("./notification");
const onBoarding = require("./Onboarding/onBoarding");
const video = require("./Onboarding/video");
const file = require("./Onboarding/file");
const fileName = require("./Onboarding/fileName");
const task = require("./Onboarding/task");
const taskName = require("./Onboarding/taskName.js");
const surveyQuestion = require("./Onboarding/surveyQuestion");
const surveyResponse = require("./Onboarding/surveyResponse");

module.exports = (router) => {
  authentication(router);
  changeHistory(router);
  company(router);
  department(router);
  document(router);
  employee(router);
  employeeAnnualTimeOff(router);
  permission(router);
  reportTo(router);
  role(router);
  socialProfile(router);
  team(router);
  timeOff(router);
  timeOffHistory(router);
  appUser(router);
  offBoarding(router);
  offBoardingQuestion(router);
  offBoardingResponse(router);
  offBoardingDocument(router);
  notification(router);
  onBoarding(router);
  video(router);
  file(router);
  fileName(router);
  task(router);
  taskName(router);
  surveyQuestion(router);
  surveyResponse(router);

  return router;
};
